### ISSUE TITLE
Update for ASCOM Platform 7

### ISSUE THREAD

**Issue by Principia4834** [Tigra-Astronomy/ASCOM-Platform-Nuget#2]
Tim, ASCOM Platform 7 is at release candidate 2 and hopefully will be fully released soon. Would you be able to update the package as Platform 7 moves to release? Rob and I who are maintaining and enhancing Green Swamp Server use the NuGet package as an essential part of both our local dev environment and the GitHub build process - it's not really feasible to install Platform 7 on GitHub.

I'm currently testing Green Swamp Server with Platform 7 and working through some breaking changes with Peter.
Thanks
Andy

**Comment by Peter-Simpson** [comment]
Hi Tim,

This may be the time to switch to the build machine package that is produced directly from the Platform build, which we discussed a couple of years back. 

There was one issue that you highlighted, which, from memory, was that the install script ran on installation rather than being content. I've fixed that and will post a new version with the Platform 7 DLLs for review. Did I remember correctly?

Best wishes, Peter

**Comment by Peter-Simpson** [comment]
Hi Andy,

I've uploaded the Platform 7 DLLs in this package: [https://www.nuget.org/packages/ASCOM.BuildEnvironment.SupportFiles7/](https://www.nuget.org/packages/ASCOM.BuildEnvironment.SupportFiles7/). Is this what you need?

Best wishes, Peter

**Comment by Principia4834** [comment]
Hi Peter

 

Thanks for creating the package. I’ve removed my explicit assembly references in the VS solution and added in the pre-release Platform 7 Nuget package. Everything built with no errors. I’ve not uploaded this to the GSS Github but I expect that it will work now – Rob and I will need to liaise on this. Your warnings about using this package are excellent.

 

I’ve now run ConformU 3 against the rebuilt GSS 1.0.8.5 in Alt Az simulator mode and all is OK. So I think we have a good solution here.

 

Regards

Andy

**Comment by Peter-Simpson** [comment]
Hi Andy,

I had second thoughts about the package name when I saw the trailing 7 get conflated with the semver version number, making the package appear to be for Platform 7.7. I've just de-listed the ASCOM.BuildEnvironment.SupportFiles7 package and uploaded the same version with a new and shorted package ID: ASCOM7.BuildEnvironment.Support at [NuGet](https://www.nuget.org/packages/ASCOM7.BuildEnvironment.Support/).

Sorry for messing you about, but its better to act before it starts to be used widely.

Best wishes, Peter

**Comment by Principia4834** [comment]
Hi Peter
Your naming concern makes perfect sense. No problem with having to unload and load up the new package. Thanks for all your help.
Regards
Andy

**Comment by Principia4834** [comment]
Package updated and tested with GSS dev environment. Thanks Peter
